name: "Dependabot auto merge"

on:
  pull_request: {}

permissions: "write-all"

jobs:

  auto-merge:

    runs-on: "ubuntu-latest"

    steps:

    - uses: "actions/checkout@v3"

    - uses: "ahmadnassri/action-dependabot-auto-merge@v2"
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
        target: "major"
        command: "rebase"
